### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by kgoldmann** [KRollenbeck/iPhone-Mirroring-EU-Activation#1]
Followed the steps and allowed full disk access, but getting a SyntaxError on running.

I have Python 3.12.5.

<img width="278" alt="Screenshot 2024-11-07 at 14 12 28" src="https://github.com/user-attachments/assets/62e9741f-2f33-4b80-9145-807afb182351">

**Comment by KRollenbeck** [comment]
Maybe you have two pythons installed? Can you check if the shortcut uses the correct version?

**Comment by KRollenbeck** [comment]
> Followed the steps and allowed full disk access, but getting a SyntaxError on running.
> 
> I have Python 3.12.5.
> 
> <img alt="Screenshot 2024-11-07 at 14 12 28" width="278" src="https://private-user-images.githubusercontent.com/8964638/383972937-62e9741f-2f33-4b80-9145-807afb182351.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwMDE4NzUsIm5iZiI6MTczMTAwMTU3NSwicGF0aCI6Ii84OTY0NjM4LzM4Mzk3MjkzNy02MmU5NzQxZi0yZjMzLTRiODAtOTE0NS04MDdhZmIxODIzNTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDdUMTc0NjE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWZkY2U5YjlhYzc4ZGZhNjQxMjVlOGNjM2YwMGQ2NTI3MjExNzk4YjMwYjUyMTI1NWUzNWUxMjZjZGEwYmY1NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.YMy58c78GGe8XrFEeeOqXchQShvj0MjUggoVoOXnkbQ">

Maybe you have two pythons installed? Can you check if the shortcut uses the correct version?

**Comment by kgoldmann** [comment]
Seems like it's using the right version to me.

<img width="1018" alt="image" src="https://github.com/user-attachments/assets/e9ddead8-699a-4c94-8ee4-626224a35275">

**Comment by KRollenbeck** [comment]
Maybe the shortcut uses a different python installation. You can try replacing the command "python3 text" with "python3 -V" or use the command "type python3" to check the location of the python installation. And then compare both and check if they are the same.

**Comment by kgoldmann** [comment]
Weirdly enough, changing the command to python -V fixed the issue and the shortcut runs perfectly fine now. 🤨

**Comment by KRollenbeck** [comment]
> Weirdly enough, changing the command to python -V fixed the issue and the shortcut runs perfectly fine now. 🤨

Nice that it worked for you :)
